
version: "3"
services:
  cw-postgres:
    container_name: cw-postgres
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_DB: planesales
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth=scram-sha-256
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - cw_network
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  cw-backend:
    build: ./backend
    container_name: cw-backend
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Moscow
    depends_on:
      - cw-postgres
    networks:
      - cw_network
    restart: unless-stopped

  cw-frontend:
    build: ./Frontend/planesales-react
    container_name: cw-frontend
    ports:
      - "3003:3000"
    networks:
      - cw_network
    environment:
      - TZ=Europe/Moscow
    depends_on:
      - cw-postgres
    restart: unless-stopped

networks:
  cw_network:
  

volumes:
  postgres_data: