
FROM bellsoft/liberica-openjdk-alpine:18.0.2.1-1


WORKDIR /app


COPY target/Pr5_spring-0.0.1-SNAPSHOT.jar /app/Pr5_spring-0.0.1-SNAPSHOT.jar


EXPOSE 8080


CMD ["java", "-jar", "Pr5_spring-0.0.1-SNAPSHOT.jar"]